language: node_js
node_js:
  - lts/*

dist: bionic
services:
  - xvfb

cache:
  directories:
  - "$HOME/.npm"

install:
  - npm ci
  - npm i -g karma-cli

jobs:
  include:
    - stage: test
      script: npm run test-firefox
